= Contributing to Spring Cloud Zuul RateLimit

Spring Cloud Zuul RateLimit is released under the Apache 2.0 license. If you would like to contribute
something, or simply want to hack on the code this document should help you get started.


== Code of Conduct
This project adheres to the Contributor Covenant link:docs/code-of-conduct.adoc[code of
conduct]. By participating, you are expected to uphold this code. Please report
unacceptable behavior to marcos.hgb@gmail.com.


== Using GitHub issues
We use GitHub issues to track bugs, enhancements and questions.

If you are reporting a bug, please help to speed up problem diagnosis by providing as much
information as possible. Ideally, that would include a small sample project that reproduces the
problem.


== Code Conventions and Housekeeping
None of these is essential for a pull request, but they will all help.  They can also be
added after the original pull request but before a merge.

* Make sure all new `.java` files to have a simple Javadoc class comment with at least an
  `@author` tag identifying you, and preferably at least a paragraph on what the class is
  for.
* Add the ASF license header comment to all new `.java` files (copy from existing files
  in the project)
* Add yourself as an `@author` to the `.java` files that you modify substantially (more
  than cosmetic changes).
* Add some Javadocs.
* A few unit tests would help a lot as well -- someone has to do it.
* If no-one else is using your branch, please rebase it against the current master (or
  other target branch in the main project).
* When writing a commit message please follow http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions],
  if you are fixing an existing issue please add `Fixes XXXX` at the end of the commit
  message (where `XXXX` is the issue number).



== Working with the code
If you don't have an IDE preference we would recommend that you use
https://spring.io/tools/sts[Spring Tools Suite] or
http://eclipse.org[Eclipse] when working with the code. We use the
http://eclipse.org/m2e/[M2Eclipse] eclipse plugin for maven support. Other IDEs and tools
should also work without issue.



=== Building from source
To build the source you will need to install
http://maven.apache.org/run-maven/index.html[Apache Maven] v3.2.3 or above and JDK 1.8.



==== Default build
The project can be built from the root directory using the standard maven command:

[indent=0]
----
	$ mvn clean install
----

If you are rebuilding often, you might also want to skip the tests and the execution of
checkstyle until you are ready to submit a pull request:

[indent=0]
----
	$ mvn clean install -DskipTests -Pfast
----



